version: "3.1"
services:

    memcached:
      image: memcached:alpine
      container_name: squeeze-info-memcached

    redis:
      image: redis:alpine
      container_name: squeeze-info-redis

    mysql:
      image: mysql:8.0
      container_name: squeeze-info-mysql
      working_dir: /application
      volumes:
        - .:/application
      environment:
        - MYSQL_ROOT_PASSWORD=root-pass
        - MYSQL_DATABASE=squeeze-info
        - MYSQL_USER=db-user-name
        - MYSQL_PASSWORD=db-user-pass
      ports:
        - "8082:3306"

    webserver:
      image: nginx:alpine
      container_name: squeeze-info-webserver
      working_dir: /application
      volumes:
          - .:/application
          - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
       - "8080:80"

    php-fpm:
      build: docker/php-fpm
      container_name: squeeze-info-php-fpm
      working_dir: /application
      volumes:
        - .:/application
        - ./docker/php-fpm/php-ini-overrides.ini:/etc/php/7.3/fpm/conf.d/99-overrides.ini

